const assets = [
  {
    type: "img",
    src: "hihat_open.png",
    id: "icon-hihat_open",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "hihat.png",
    id: "icon-hihat",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "snare.png",
    id: "icon-snare",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "kick.png",
    id: "icon-kick",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "tom_high.png",
    id: "icon-tom_high",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "tom_mid.png",
    id: "icon-tom_mid",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "tom_low.png",
    id: "icon-tom_low",
    drumkit: "independent",
  },
  {
    type: "img",
    src: "crash.png",
    id: "icon-crash",
    drumkit: "independent",
  },
  {
    type: "sound",
    src: "drumkit_indie/kick.mp3",
    id: "indie-kick",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/snare.mp3",
    id: "indie-snare",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/hihat.mp3",
    id: "indie-hihat",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/hihat_open.mp3",
    id: "indie-hihat_open",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/tom_high.mp3",
    id: "indie-tom_high",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/tom_mid.mp3",
    id: "indie-tom_mid",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/tom_low.mp3",
    id: "indie-tom_low",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_indie/crash.mp3",
    id: "indie-crash",
    drumkit: "indie",
  },
  {
    type: "sound",
    src: "drumkit_metal/kick.mp3",
    id: "metal-kick",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/snare.mp3",
    id: "metal-snare",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/hihat.mp3",
    id: "metal-hihat",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/hihat_open.mp3",
    id: "metal-hihat_open",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/tom_high.mp3",
    id: "metal-tom_high",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/tom_mid.mp3",
    id: "metal-tom_mid",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/tom_low.mp3",
    id: "metal-tom_low",
    drumkit: "metal",
  },
  {
    type: "sound",
    src: "drumkit_metal/crash.mp3",
    id: "metal-crash",
    drumkit: "metal",
  },
];

export default assets;
